# AUTO-GENERATED by tools/gen_assets.py - DO NOT EDIT BY HAND.
class_name ArtIndex

const CELL := Vector2i(24, 32)
const COLS := 8
const DIRS := ["down", "up", "left", "right"]
const FRAMES := {"idle": [0, 1], "walk": [2, 3, 4, 5], "attack": [6, 7]}
const ICON_INDEX := {"iron_sword": 0, "steel_blade": 1, "golden_sword": 2, "rusty_dagger": 3, "battle_axe": 4, "oak_staff": 5, "hunter_bow": 6, "tunic_cloth": 7, "leather_vest": 8, "iron_plate": 9, "royal_plate": 10, "mage_robe": 11, "leather_cap": 12, "iron_helm": 13, "golden_crown": 14, "wizard_hat": 15, "shadow_hood": 16, "cloth_pants": 17, "leather_pants": 18, "iron_greaves": 19, "cloth_shoes": 20, "leather_boots": 21, "iron_boots": 22, "red_cloak": 23, "royal_cloak": 24, "forest_cloak": 25}
const ICON_GRID := Vector2i(8, 16)
const TERRAIN_INDEX := {"grass": 0, "grass2": 1, "sand": 2, "sand2": 3, "snow": 4, "swamp": 5, "stone": 6, "water": 7, "dirt": 8, "cobble": 9, "wood": 10, "cave": 11}
const PROP_INDEX := {"tree": 0, "rock": 1, "bush": 2, "flower": 3, "chest": 4, "stairs": 5, "sign": 6, "torch": 7}
const ENEMIES := {"slime": {"w": 24, "h": 24, "frames": 4, "cols": 4}, "bat": {"w": 24, "h": 24, "frames": 4, "cols": 4}, "goblin": {"w": 24, "h": 24, "frames": 4, "cols": 4}, "skeleton": {"w": 24, "h": 24, "frames": 4, "cols": 4}, "orc": {"w": 24, "h": 24, "frames": 4, "cols": 4}, "demon": {"w": 24, "h": 24, "frames": 4, "cols": 4}, "dragon": {"w": 32, "h": 32, "frames": 4, "cols": 4}}
const EQUIPMENT_SLOTS := ["chest", "helmet", "legs", "boots", "weapon", "accessory"]
const EQUIPMENT_IDS := {"chest": ["tunic_cloth", "leather_vest", "iron_plate", "royal_plate", "mage_robe"], "helmet": ["leather_cap", "iron_helm", "golden_crown", "wizard_hat", "shadow_hood"], "legs": ["cloth_pants", "leather_pants", "iron_greaves"], "boots": ["cloth_shoes", "leather_boots", "iron_boots"], "weapon": ["iron_sword", "steel_blade", "golden_sword", "rusty_dagger", "battle_axe", "oak_staff", "hunter_bow"], "accessory": ["red_cloak", "royal_cloak", "forest_cloak"]}
